### ISSUE TITLE
New Kedro 0.18.14

### ISSUE THREAD

**Issue by erwinpaillacan** [noklam/kedro-softfail-runner#1]
I wanted to used this runner. I had to make some changes to make it work in 0.18.14 and dataset factory

Specifically.

I had to replace 

`unsatisfied = pipeline.inputs() - set(catalog.list())`

 https://github.com/noklam/kedro-softfail-runner/blob/03091926fe5825c9f9a3428fdb65b4728e7ff959/kedro_softfail_runner/core.py#L150C9-L150C62

by

```
# Check which datasets used in the pipeline are in the catalog or match
# a pattern in the catalog
registered_ds = [ds for ds in pipeline.data_sets() if ds in catalog]

# Check if there are any input datasets that aren't in the catalog and
# don't match a pattern in the catalog.
unsatisfied = pipeline.inputs() - set(registered_ds)
```
https://github.com/kedro-org/kedro/blob/df9f174864640de193b2b85f04d0c3e8aee7d22c/kedro/runner/runner.py#L79C9-L79C77

**Comment by noklam** [comment]
Sorry for the delayed response, I missed the notification. Thanks @erwinpaillacan, I have updated and release a 0.0.3 version.
